name: Ensure app compliance with Ledger guidelines

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  check_app_compliance:
    name: Call Ledger app_compliance
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/app_compliance.yml@master
